### ISSUE TITLE
Feature request: module rewrite

### ISSUE THREAD

**Issue by renarsvilnis** [arcs-/MediumButton#11]
Hi,
started out with `medium-editor`, needed a create a button that sets a custom style (tag and class).
Found this `medium-editor` extension, which worked but it wasn't able to unformat a portion of a previously selected text. 

Started to look at the code and begin by doing a complete rewrite of the module (adding code seperation, removing global variables), but after spending an hour or two went to explore the `medium-editor` documentation on extensions and realised this package is not needed anymore.

The same can be achieved by the code below, but with a additional dependency, but adding feature to format/unformat a portion of the initial selection. Such as removing heading style for some of the words.

``` javascript
// add "rangy" dependency, makes working with selections trivial
// Ref: https://github.com/timdown/rangy
import rangy from 'rangy/lib/rangy-core';
import 'rangy/lib/rangy-classapplier';

// won't initiate if already initiated
rangy.init();

/**
 * Basic custom button that highlights text
 * Based on: https://github.com/yabwe/medium-editor/blob/5.15.1/src/js/extensions/WALKTHROUGH-BUTTON.md
 */
const HighlighterButton = MediumEditor.extensions.button.extend({
  tagNames: ['mark'],
  contentDefault: '<b>H</b>',
  aria: 'Highlight',
  // Note: reference the Button interface for more options depending on needs
  // Ref: https://github.com/yabwe/medium-editor/tree/5.15.1/src/js/extensions#button

  init: function () {
    // call parent class, similar as in ES6 classes super() call
    MediumEditor.extensions.button.prototype.init.call(this);

    // rangy takes cares of all of the magic
    // TODO: should create an class applier for each element tag?
    this.classApplier = rangy.createClassApplier('custom-header', {
      elementTagName: this.tagNames[0],
      normalize: true
    });
  },

  handleClick: function (event) {
    this.classApplier.toggleSelection();
  }
});
```

`HighlighterButton` is used the same this module:

``` javascript
const el = document.getElementById('text-editor');
const config = {
  toolbar: {
    buttons: [
      'highlight'
    ]
  },
  extensions: {
    imageDragging: {},
    'highlight': new HighlighterButton()
  }
};

const editor = new MediumEditor(el, config);

```

I think it's an good idea to wrap this code in a function, similar as this module, so that no need to initiate and add `rangy` manually.

**Comment by arcs-** [comment]
You are right, this extension needs a rewrite. But the solution with rangy is not working for all cases. There are many but as an example syntax highliting.
