### ISSUE TITLE
Get the parent node of the selected text in "action"

### ISSUE THREAD

**Issue by n457** [arcs-/MediumButton#13]
Hi !
Thanks for creating this nice MediumEditor extension.

I need to get the parent node of the selected text once the button is clicked.
Is there a way to easily get that ? Or maybe by implementing :

``` javascript
var editor = new MediumEditor('.editor', {
    buttons: ['pop'],
    extensions: {

      'pop': new MediumButton({
        label:'POP', 
        action: function(html, mark, htmlParentNode){
          console.log(htmlParentNode);
          return html; 
        }
      })

    }
});
```

?
Have a nice day

**Comment by arcs-** [comment]
The commit from @hasentopf should fix it for you.
