### ISSUE TITLE
Not applying changes

### ISSUE THREAD

**Issue by Hube2** [arcs-/MediumButton#14]
I'm using Medium button, but it is not always working for my textarea. The only way that I can consistently get a new button to update the content is if I apply one of the standard Medium Editor buttons to the content after it. I think it might have something to do with this https://github.com/yabwe/medium-editor/issues/942, but I'm not sure.

Is this still active, can anyone help me with this?

**Comment by Hube2** [comment]
Thought I'd stop back and post my solution, just in case someone else is having the same problem, although it's just a hack to make it work for what I'm using it for and not real a solution. Basically I bind a `DOMSubtreeModified` to every editor element and then call `editor.events.updateInput()` every time the editor element is modified to force the changes to take place.

```

    var editor = new MediumEditor($selector, $object);

    if (editor.elements.length) {
      var elements = editor.elements;

      for (i=0; i<editor.elements.length; i++) {
        // bind DOMSubtreeModified to each editor element
        var editorId = elements[i].id;

        $('#'+editorId).bind('DOMSubtreeModified', function(e) {
          // make editor element something usable by editor.events.updateInput()
          var $target = document.getElementById(e.currentTarget.id);
          // find the textarea element associated with the editor element
          // and make it usable by editor.events.updateInput()
          // not sure this matters, but specific to how i'm using it
          var $targetObj;
          $('textarea[medium-editor-textarea-id="'+e.currentTarget.id+'"]').each(function(index, element) {
            $targetObj = document.getElementById(element.id);
          });
          editor.events.updateInput($target, $targetObj);
        });
      }
    }
```

**Comment by arcs-** [comment]
What is the simplest way to reproduce this error? 
Also, did you check the latest version? I might have fixed it.

In general, this repository is not very active.

**Comment by Hube2** [comment]
It appears that whatever you've changed has corrected the issue for me.  I've commented out my work around in my code, will keep an eye on it, see what happens. Will report back if I still see a problem.
