### ISSUE TITLE
Allow using with MediumEditor 5.x.x

### ISSUE THREAD

**Issue by CupOfTea696** [arcs-/MediumButton#16]
Hi, 

You've recently added a dependency to the `bower.json` for MediumEditor 4.x.x (see [here](https://github.com/arcs-/medium-button/commit/d0c2ca807302123811e862b1cb96bab6711e0c92#commitcomment-20250309)), however, this plugin worked fine for me with MediumEditor 5.x.x. Could this please be added to the dependencies?

Thanks.

**Comment by arcs-** [comment]
Thanks, I actually tested it with 5.x but forgot the dependency.
