### ISSUE TITLE
Start value for button - how to have a custom string

### ISSUE THREAD

**Issue by shaanvaidya** [arcs-/MediumButton#22]
I am enclosing the selected part in a span element. I want to provide a unique id for each such selection so as to use them in my code later.
I tried this. 
```
var selectionid = 0;
...
    start:'<span class="selected" id='+selectionid+'style="background-color: #FFFF00">',
    end:'</span>',
```
Any ideas?

**Comment by arcs-** [comment]
Yeah, sorry. That won't work, and right now there is no way you can do this. The code needs rewriting, and this feature should be added. Sadly I do not have any time, I wrote it for a project that I do not longer maintain.
