### ISSUE TITLE
Uncaught TypeError: self.base.chackContentChanged is not a function

### ISSUE THREAD

**Issue by teakap** [arcs-/MediumButton#24]
Hello! I am instantiating the plug in in my ember app, on the `afterRender` hook like so:

```javascript

let elements = document.querySelector('.comment-content-content'); 
    		    	
var editor = new MediumEditor(elements, {
        disableEditing: true,
    	  toolbar: {
    	    buttons: ['createCommentSection']
    	  },
    	extensions: {
          'createCommentSection': new MediumButton({
    			label: 'Do post request with the selected text',
    		    action: function (html, mark, parent) {    				                    _this.send('createCommentSection', html, mark, parent) ;
    				         return html ;
    		   }
    		})
    	}
    })
```
In the `createCommentSection` action am doing something like this: 
```javascript
let highlightedText = text ;
let oldContent = this.get('comment.content') ;
let newContent = oldContent.replace(highlightedText, `<span style="background-color: #ffff94">${highlightedText}</span>`) ;
```
as well as making a post request with the content.
My issue is, that **sometimes** (unfortunately I can't define when. Because in the same exact circumstances it behaves differently), I get this error:
![uncaught_typeerror](https://user-images.githubusercontent.com/13741777/33445152-688eebd4-d5fc-11e7-8be9-797eee74c4e1.png)

Any ideas why ? 

_P.S.: I am trying to use it on top of froala-editor which I use for displaying comments. That's why I want a custom function for highlighting  since I need to also update the content of the editor_.

**Comment by arcs-** [comment]
Hard to say why without more details. 
`self.base.checkContentChanged()` is the function I call at the end to notify MediumEditor that a change might have occurred. Could it be that you replace the content with null (or similar)?

**Comment by teakap** [comment]
Hey I will provide more in the next days. What I meant is that I am manipulating the[ froala's editor](https://www.froala.com/wysiwyg-editor) content. I am using the medium editor, with the medium button plug-ins on top of froala editor. Thanks for replying! Will send more info soon :  )

**Comment by teakap** [comment]
So the thing is, I am not modifying the content of the editor at all. I am currently using medium-editor && medium-button, in order to create custom buttons which highlight/modify the content of the froala editor accordingly. Whenever a button gets clicked, I am calling a custom function to do that.  I am also making use of the `disableEditing: true` in order not to use the editing mode of the medium-editor at all. Currently, the functionality I want, works most of the time. But nevertheless I get the error mentioned above. 

Should you notify the MediumEditor, even there are no changes affiliated with MediumButton or MediumEditor? 

I know it's probably not the best way to use all 3 plug-ins like this. So it might be a really specific use-case that doesn't need resolving. Not sure yet though.. Tell me if you need anything more details :)

Thanks

**Comment by teakap** [comment]
Didn't find the time to check further in the bug. But since it's kind of a special case, and no-one else had a familiar issue, I think I'll close this issue for now. Thanks for the help :)
