### ISSUE TITLE
no longer works with medium-editor

### ISSUE THREAD

**Issue by ryedin** [arcs-/MediumButton#4]
I've upgraded to medium-editor 5.x now, and this extension no longer works. Do you have plans to update it to work with the 5.x API?

**Comment by glovebx** [comment]
Still works.
Change source of demo's index.html from:
---> buttons: ['bold', 'h2', 'JS', 'warning', 'pop'],
to
---> toolbar: {
          buttons: ['bold', 'h2', 'JS', 'warning', 'pop']
       },
and it worked for me.

**Comment by ryedin** [comment]
Aha!!!

Thank you :)

Sorry for the false alarm.

**Comment by Hube2** [comment]
Is this still working? Maybe someone can help me here. I'm following the instructions with the exception of the change mentioned here and I'm getting nowhere fast. Here is the exact code I'm using, I've added two buttons just to see if it is working but they do not get added to the toolbar

```
jQuery(document).ready(function($){
    var editor = new MediumEditor('[data-key="field_57f4f2b9fc44f"] textarea', {
        toolbar: {buttons: ['bold', 'italic', 'underline', 'em', 'b']},
        extenstions: {
            'em': new MediumButton({label:'em', start:'<em>', end:'</em>'}),
            'b':  new MediumButton({label:'BOLD', start:'<b>', end:'</b>'})
        },
        disableReturn: true,
        disableDoubleReturn: true, disableExtraSpaces: true, disableEditing: false, spellcheck: false, targetBlank: false,
        placeholder: {
            text: 'This will be the placeholder text if entered',
            hideOnClick: false
        }
    });
});
```

**Comment by Hube2** [comment]
NM, I can't believe I've been beating my head on my desk over a stupid type

**Comment by arcs-** [comment]
intructsions updated
