### ISSUE TITLE
Insert html outside the paragraph

### ISSUE THREAD

**Issue by lotestudio** [arcs-/MediumButton#6]
I can't understand something :(...
How to make button to insert fro example some div with class but want this div to be outside of the pragraph.
For example:
I have this text:

```
    <p>Lorem ipsum. Lorem Ipsum. Lorem Ipsum.</p>
```

Want to make this markup:

```
    <p>Lorem ipsum.</p>
    <div class="someclass">Lorem Ipsum.</div>
    <p>Lorem Ipsum.</p>
```

Not:

```
    <p>Lorem ipsum.
    <div class="someclass">Lorem Ipsum.</div>
    Lorem Ipsum.</p>

```

**Comment by jorgedavila25** [comment]
Also facing this same issue. @lotestudio did you figure this out by any chance?

**Comment by hasentopf** [comment]
Also facing this same issue. @jorgedavila25 or @lotestudio did you figure this out by any chance?

**Comment by arcs-** [comment]
Should be fixed thanks to @hasentopf
